### ISSUE TITLE
charcode dependency incompatible.

### ISSUE THREAD

**Issue by phonghoang2k** [raycardillo/dart_phonetics#10]
> Because every version of flutter_test from sdk depends on charcode 1.2.0 and dart_phonetics 1.0.1 depends on charcode ^1.3.1, flutter_test from sdk is incompatible with dart_phonetics 1.0.1.
> And because no versions of dart_phonetics match >1.0.1 <2.0.0, flutter_test from sdk is incompatible with dart_phonetics ^1.0.1.

Look like the charcode in this plugin is a little bit higher than the sdk has. Please downgrade this dependency into 1.2.0.
Thanks.

**Comment by raycardillo** [comment]
You should be able to use the dependency override feature until Flutter `stable` catches up.
https://dart.dev/tools/pub/dependencies#dependency-overrides

You can also try the `master` channel because flutter has made this update to the version of `charcode` also already.
https://github.com/flutter/flutter/blob/25ba467b5a9bf1a3a9c84ca70d7c807ac4da5200/packages/flutter_test/pubspec.yaml#L35

Finally, notice that the new version of this library is a major version change because of some small breaking changes but it’s fully compatible with dart. The latest version of `charcode` isn’t anything significant but I want to be at their latest version for the benefit of dart users.

In the meantime, the workarounds above will work for Flutter. Please confirm after you test.

**Comment by phonghoang2k** [comment]
Oh, i've thought about this workaround before. Anyway, thanks a lot.
